recyclingApplication/homepage/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    # path("<int:month>", views.monthly_challenge_by_number),
    # Naming a path can be use in redirection
    # path("<str:month>", views.monthly_challenge, name='monthly_challenge'),
]

recyclingApplication/portal/urls.py
from django.urls import path
from portal.views.settingView import  CustomPasswordResetView
from portal.views.dashboardView import DashboardView
from portal.views.authView import LoginView, LogoutView
from portal.views.userVieww import CreateUserView
from portal.views.volunteerView import AddVolunteerView, VolunteersView, VolunteerDetailsView
from portal.views.requestsView import RequestsView, RequestDetailsView, AvailableRequestView, ClaimRequestView, VolunteerRequestView, CompleteRequestView

app_name = "portal"

urlpatterns = [
    path("login", LoginView.as_view(), name="portal_login"),
    path("logout", LogoutView.as_view(), name="portal_logout"),
    path("requests", RequestsView.as_view(), name="requests"),
    path("request-details/<int:id>", RequestDetailsView.as_view(), name="request_details"),
    path("request-available", AvailableRequestView.as_view(), name="request_available"),
    path("request-volunteer/<int:user_id>", VolunteerRequestView.as_view(), name="request_volunteer"),
    path("requests/claim/<int:request_id>/", ClaimRequestView.as_view(), name="claim_request"),
    path("requests/complete/<int:request_id>/", CompleteRequestView.as_view(), name="complete_request"),
    path("volunteers", VolunteersView.as_view(), name="volunteers"),
    path("add-volunteer", AddVolunteerView.as_view(), name="add_volunteer"),
    path("volunteer-details/<int:id>", VolunteerDetailsView.as_view(), name="volunteer_details"),
    path("settings", CustomPasswordResetView.as_view(), name="settings"),
    path("dashboard", DashboardView.as_view(), name="dashboard"),
    path("create-user", CreateUserView.as_view(), name="create_user"),
]

recyclingApplication/recyclingApplication/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('portal/', include('portal.urls'))
]

recyclingApplication/homepage/models.py
from django.db import models
from django.contrib.auth.models import User as AuthUser

# Create your models here.
class Request(models.Model):
  STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
    ]
  
  first_name = models.CharField(max_length=256)
  last_name = models.CharField(max_length=256)
  email = models.EmailField(max_length=256)
  phone = models.CharField(max_length=20)
  address = models.CharField(max_length=256)
  city = models.CharField(max_length=64)
  state = models.CharField(max_length=64)
  country = models.CharField(max_length=64)
  postal_code = models.CharField(max_length=64)
  status = models.CharField(max_length=32, choices=STATUS_CHOICES, default='pending')
  date_created = models.DateTimeField(auto_now_add=False)
  date_completed = models.DateTimeField(null=True, blank=True)
  token = models.CharField(max_length=512)
  claimed_by = models.ForeignKey(AuthUser, null=True, blank=True, on_delete=models.SET_NULL, related_name="claimed_requests")

  def __str__(self):
    return self.first_name + " " + self.last_name

recyclingApplication/homepage/forms.py
from django import forms
from .models import Request
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

class CreateRequestForm(forms.ModelForm):
    phone_validator = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Phone number must be entered in the format: '+123456789'. Up to 15 digits allowed."
    )

    phone = forms.CharField(
        max_length=20, 
        validators=[phone_validator],
        widget=forms.TextInput(attrs={'placeholder': 'Enter your phone number'})
    )

    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Enter your email'})
    )

    postal_code = forms.CharField(
        max_length=10,
        widget=forms.TextInput(attrs={'placeholder': 'Enter postal code'})
    )

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if not first_name.isalpha():
            raise ValidationError("First name should only contain letters.")
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if not last_name.isalpha():
            raise ValidationError("Last name should only contain letters.")
        return last_name

    def clean_postal_code(self):
        postal_code = self.cleaned_data.get('postal_code')
        if not postal_code.isalnum():
            raise ValidationError("Postal code should only contain letters and numbers.")
        return postal_code

    class Meta:
        model = Request
        fields = ['first_name', 'last_name', 'email', 'phone',
                  'address', 'city', 'state', 'country', 'postal_code']


class RequestByTokenForm(forms.Form):
    token = forms.CharField(max_length=512, required=True, label="Enter token")

recyclingApplication/homepage/views.py
import secrets

from django.shortcuts import render
from django.views import View
from .forms import CreateRequestForm, RequestByTokenForm
from django.utils import timezone
from portal.services.email_services import EmailService
from homepage.models import Request

class IndexView(View):
    def get(self, request):
        create_form = CreateRequestForm()
        token_form = RequestByTokenForm()
        return render(request, "homepage/index.html", {
            "createRequestForm": create_form,
            "tokenForm": token_form
        })

    def post(self, request):
        create_form = CreateRequestForm(request.POST) if "request_create" in request.POST else CreateRequestForm()
        token_form = RequestByTokenForm(request.POST) if "request_lookup" in request.POST else RequestByTokenForm()

        # Handle request creation
        if "request_create" in request.POST:
            if create_form.is_valid():
                instance = create_form.save(commit=False)
                instance.date_created = timezone.now().date()
                instance.status = "pending"
                instance.token = secrets.token_urlsafe(16)

                instance.save()

                # Send email
                email_service = EmailService()
                email_service.send_welcome_email(instance=instance)

                return render(request, "homepage/thank_you.html", {
                    'token': instance.token
                })

        # Handle request lookup
        elif "request_lookup" in request.POST:
            if token_form.is_valid():
                token = token_form.cleaned_data["token"]
                request_obj = Request.objects.filter(token=token).first()

                if request_obj:
                    return render(request, "homepage/request_details.html", {
                        "request_obj": request_obj
                    })
                else:
                    token_form.add_error("token", "No request found with this token.")

        return render(request, "homepage/index.html", {
            "createRequestForm": create_form,
            "tokenForm": token_form
        })

recyclingApplication/homepage/templates/homepage/includes/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'challenges/css/footer.css' %}" />
<footer class="text-light py-4" style="bottom:0">
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <h5>Quick Links</h5>
              <ul class="list-unstyled">
                  <li><a href="{% url 'index' %}" class="text-light">Home</a></li>
                  <li><a href="{% url 'index' %}#desc-section" class="text-light">About Us</a></li>
                  <li><a href="{% url 'index' %}#requestForm" class="text-light">Submit Request</a></li>
              </ul>
          </div>
          <div class="col-md-4">
              <h5>Follow Us</h5>
              <a href="#" class="text-light me-3"><i class="bi bi-facebook"></i> Facebook</a>
              <a href="#" class="text-light me-3"><i class="bi bi-twitter"></i> Twitter</a>
              <a href="#" class="text-light"><i class="bi bi-instagram"></i> Instagram</a>
          </div>
          <div class="col-md-4">
              <h5>Contact</h5>
              <p>Email: info@recyclecharity.com</p>
              <p>Phone: +1 (123) 456-7890</p>
          </div>
      </div>
  </div>
</footer>

recyclingApplication/homepage/templates/homepage/includes/header.html
{% load static %}

{% comment %} {{ active_page }} {% endcomment %}
<link rel="stylesheet" href="{% static 'challenges/css/header.css' %}" />
<nav class="navbar navbar-expand-sm navbar-dark sticky-top">
  <div class="container-fluid  mx-5">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="{% static "images/logo.png" %}" alt="Logo" height="45"  class="d-inline-block me-5">
      Recycle For Charity
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
      {% comment %} <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url "index" %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "index" %}">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "index" %}">Contact</a>
        </li>
      </ul> {% endcomment %}
      <div class="me-auto"></div>
        <button class="btn btn-primary btn-color-primary" 
        type="button"  onclick="window.location.href='{% url 'portal:portal_login' %}';">Login</button>
    </div>
  </div>
</nav>